CREATE TABLE IF NOT EXISTS book(
   id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
   vendor_code integer,
   title varchar(255) NOT NULL,
   publication_year integer,
   description varchar(2000),
   brand varchar(255) NOT NULL,
   stock integer,
   price bigint
);
